/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./features/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        cream: "#FAF9F6",
        "near-black": "#211F1A",
        "earth-green": "#2D6A4F",
        "earth-green-dark": "#1E4D38",
        "card-bg": "#F3F1EC",
        muted: "#8A8172",
        "border-color-subtle": "#EAE7E0",
        // Warm-neutral repalette (dashboard redesign — Session 1 tokens)
        "page-bg": "#F8F4EC",
        "ink-muted": "#A79E8E",
        "ink-on-dark": "#EDE7DA",
        "ink-muted-on-dark": "#9C9483",
        "emerald-deep": "#1E3226",
        "emerald-active": "#2A4436",
        "nav-inactive": "#8FA294",
        "teal-bright": "#6FDFB8",
        "teal-mid": "#2F8F6D",
        "teal-soft": "#9FD9C4",
        "goal-card": "#FCFAF4",
        "border-warm": "#EDE6D8",
        "border-warm-subtle": "#EFE9DC",
        "toggle-glyph": "#A8C4AE",
        // Manual dark theme (app screens)
        "dark-bg": "#0B1216",
        "dark-card": "#111A1F",
        "dark-border": "#263238",
        // Landing-page-only dark palette
        "landing-dark-bg": "#0A0A0F",
        "landing-dark-card": "#14141F",
        "landing-dark-border": "#1E1E2E",
        ink: "#FAFAFA",
        "landing-ink-dim": "#8888A0",
        "landing-primary": "#6E5CE7",
        // Landing-page redesign (light / warm palette)
        "lp-bg": "#F5F1EA",
        "lp-ink": "#211F1A",
        "lp-muted": "#6B6B6B",
        "lp-green": "#3D5247",
        "lp-green-hover": "#2A3B31",
        "lp-green-medallion": "#24312A",
        "lp-teal": "#6FDFB8",
        "lp-amber": "#E09F3E",
        "lp-card": "#FFFFFF",
        "lp-border": "#E4DED0",
        "lp-border-strong": "#D8D2C4",
        "lp-panel-green": "#EEF3EE",
        "lp-panel-teal": "#EAF7F0",
        "lp-panel-amber": "#FBF1E1",
      },
      fontFamily: {
        sans: ['Inter-Regular', 'Inter', '-apple-system', 'BlinkMacSystemFont', 'SF Pro Text', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'inter-regular': ['Inter-Regular', 'Inter', 'System', 'sans-serif'],
        'inter-medium': ['Inter-Medium', 'Inter', 'System', 'sans-serif'],
        'inter-semibold': ['Inter-SemiBold', 'Inter', 'System', 'sans-serif'],
        'inter-bold': ['Inter-Bold', 'Inter', 'System', 'sans-serif'],
        'inter-extrabold': ['Inter-ExtraBold', 'Inter', 'System', 'sans-serif'],
      },
      fontSize: {
        '3xs': ['11px', { lineHeight: '15px' }],
        '2xs': ['12px', { lineHeight: '17px' }],
        xs:    ['13px', { lineHeight: '18px' }],
        sm:    ['14px', { lineHeight: '20px' }],
        base:  ['16px', { lineHeight: '24px' }],
        lg:    ['18px', { lineHeight: '24px' }],
        xl:    ['20px', { lineHeight: '26px' }],
        '2xl': ['28px', { lineHeight: '34px' }],
        '3xl': ['30px', { lineHeight: '38px' }],
        '4xl': ['36px', { lineHeight: '44px' }],
        // Legacy Echo aliases now resolve to the shared readable semantic scale.
        'echo-2xs':      ['12px', { lineHeight: '17px' }],
        'echo-xs':       ['13px', { lineHeight: '18px' }],
        'echo-sm':       ['14px', { lineHeight: '20px' }],
        'echo-sm-loose': ['14px', { lineHeight: '21px' }],
        'echo-base':     ['17px', { lineHeight: '27px' }],
        'echo-md':       ['18px', { lineHeight: '24px' }],
        'echo-lg':       ['28px', { lineHeight: '34px' }],
      },
    },
  },
  plugins: [],
};
