-- Synthetic child-table prerequisites for Migration 073 tests only (applied after manual-v1-db-scaffold.sql,
-- before 072/073). Columns mirror the production tables that goal_card_v1 reads; it certifies nothing about the full chain.
alter table public.goals add column completed_at timestamptz, add column archived_at timestamptz;
create table public.milestones(id uuid primary key default gen_random_uuid(),goal_id uuid not null references public.goals on delete cascade,user_id uuid not null references auth.users on delete cascade,title text not null,description text,due_date date,completed_at timestamptz,sort_order integer not null default 0,created_at timestamptz not null default now(),kind text not null default 'achievement',parent_id uuid references public.milestones on delete cascade,target_count integer);
create table public.tasks(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,goal_id uuid not null references public.goals on delete cascade,title text not null,description text,completion_mode text not null default 'binary',target_quantity numeric,quantity_unit text,status text not null default 'active',due_date date,sort_order integer not null default 0,created_at timestamptz not null default now());
create table public.task_schedules(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,task_id uuid not null references public.tasks on delete cascade,version integer not null default 1,recurrence_kind text not null,interval_count integer not null default 1,weekdays smallint[] not null default '{}',target_count integer,start_date date not null,end_date date,local_time time,timezone text not null,is_active boolean not null default true);
create table public.task_occurrences(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,task_id uuid not null references public.tasks on delete cascade,schedule_id uuid references public.task_schedules,occurrence_key text not null,scheduled_local_date date,scheduled_local_time time,status text not null default 'pending',actual_quantity numeric,completed_at timestamptz);
create table public.entries(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,entry_type text not null,title text not null default '',plain_text text not null default '',archived boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.entry_goal_links(id uuid primary key default gen_random_uuid(),entry_id uuid not null references public.entries on delete cascade,goal_id uuid not null references public.goals on delete cascade,created_at timestamptz not null default now(),unique(entry_id,goal_id));
