create role anon; create role authenticated; create role service_role bypassrls;
create schema auth; create schema extensions;
create extension pgcrypto with schema extensions;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
create table public.profiles(id uuid primary key references auth.users on delete cascade,timezone text not null default 'UTC');
create table public.goals(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users on delete cascade,title text not null,category text not null,description text,status text not null default 'active',progress numeric not null default 0,deadline timestamptz,created_at timestamptz not null default now(),updated_at timestamptz default now(),visibility text default 'private',is_private boolean default true,smart_data jsonb default '{}',ai_generated boolean default false,previous_goal_id uuid,color_theme text,project_id uuid,space_id uuid,community_id uuid);
alter table public.goals enable row level security;
create policy owner on public.goals for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant usage on schema auth to authenticated;
grant all on public.goals to authenticated,service_role;
grant select,update on public.profiles to authenticated;
grant usage on schema public to anon,authenticated,service_role;
