export const CONSTELLATION_COPY = {
  emptyEyebrow: 'Your Constellation',
  emptyHeadline: "A quiet map of who you're becoming.",
  emptyBody: "Nodes here aren't clicked into being — they emerge from goals you set and reflections you keep. Ohara withholds a node until the pattern is real.",
  emptyGateGoals: 'Set 3 goals',
  emptyGateEchoes: 'Write 10 Echoes',
  emptyFooter: "You're one node so far. That's enough to begin.",
  earnedEyebrow: "Coming when it's earned",
  earnedKinds: 'Ambitions · Goals · Reflections · Traits · Tensions',
  seasonOnlyHeadline: 'Your Constellation begins with this season.',
  patternsFormingHeadline: 'Your patterns are still forming.',
  lockedHeadline: 'Constellation is not available yet.',
  graphUnavailable: 'Your activity progress could not be loaded. Please try again.',
  budLabel: 'Bud',
  roseLabel: 'Rose',
  thornLabel: 'Thorn',
} as const;
