export const CONSTELLATION_COPY = {
  emptyEyebrow: 'Your Constellation',
  emptyHeadline: "A quiet map of who you're becoming.",
  emptyBody: "Nodes here aren't clicked into being — they emerge from goals you set and reflections you keep. Ohara withholds a node until the pattern is real.",
  emptyFooter: "You're one node so far. That's enough to begin.",
  earnedEyebrow: "Coming when it's earned",
  earnedKinds: 'Ambitions · Goals · Reflections · Traits · Tensions',
  seasonOnlyHeadline: 'Your Constellation begins with this season.',
  seasonOnlyBody: 'Set a goal or write an entry and it takes shape here. Nothing is gated — this view stays quiet until you give it something to map.',
  graphUnavailable: 'Constellation could not be loaded. Please try again.',
  staleRefresh: 'Refresh failed. Showing the last successfully loaded Constellation.',
  budLabel: 'Bud',
  roseLabel: 'Rose',
  thornLabel: 'Thorn',
} as const;
