export const CONSTELLATION_COPY = {
  emptyEyebrow: 'Your Constellation',
  emptyHeadline: "A quiet map of who you're becoming.",
  emptyBody: "Nodes here aren't clicked into being — they emerge from goals you set and reflections you keep. Ohara withholds a node until the pattern is real.",
  emptyGateGoals: 'Set 3 goals',
  emptyGateEchoes: 'Write 10 Echoes',
  emptyFooter: "You're one node so far. That's enough to begin.",
  earnedEyebrow: "Coming when it's earned",
  earnedKinds: 'Ambitions · Goals · Reflections · Traits · Tensions',
  seasonOnlyHeadline: 'Your Constellation begins with this season.',
  seasonOnlyBody: 'Your access is open. No goal, ambition, or proven pattern has qualified yet, so this view stays intentionally quiet.',
  patternsFormingHeadline: 'Your patterns are still forming.',
  patternsFormingBody: 'Your goals and Echoes are creating source activity, but Ohara has not proven a pattern strongly enough to place it here yet.',
  lockedHeadline: 'Constellation is not available yet.',
  lockedBody: 'Keep setting real goals and reflecting in Echo. Access opens after three non-draft goals and ten Echoes.',
  graphUnavailable: 'Constellation could not be loaded. Please try again.',
  staleRefresh: 'Refresh failed. Showing the last successfully loaded Constellation.',
  budLabel: 'Bud',
  roseLabel: 'Rose',
  thornLabel: 'Thorn',
} as const;
