import type { GoalWithMeasurables, ActivityEntry } from '../types';

export const MOCK_GOALS: GoalWithMeasurables[] = [
  {
    id: '1',
    userId: 'mock-user',
    title: 'Run a 5K',
    description: 'Train for and complete a 5K race by summer',
    category: 'body',
    colorTheme: 'ember',
    deadline: new Date('2026-06-15'),
    isPublic: false,
    progress: 35,
    status: 'active',
    aiGenerated: false,
    smartData: null,
    projectId: null,
    createdAt: new Date('2026-03-20'),
    updatedAt: new Date('2026-03-28'),
    measurables: [
      { id: 'm1', goalId: '1', title: 'Weekly runs', type: 'counter', targetValue: 5, targetUnit: 'runs', frequency: 'weekly', currentValue: 2, isAiSuggested: true, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() },
      { id: 'm2', goalId: '1', title: 'Drink 3L water daily', type: 'habit', targetValue: 3, targetUnit: 'liters', frequency: 'daily', currentValue: 1, isAiSuggested: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
      { id: 'm3', goalId: '1', title: 'Journal run reflections', type: 'checklist', targetValue: null, targetUnit: null, frequency: 'weekly', currentValue: 0, isAiSuggested: false, sortOrder: 2, createdAt: new Date(), updatedAt: new Date() },
    ],
  },
  {
    id: '2',
    userId: 'mock-user',
    title: 'Learn Conversational Spanish',
    description: 'Reach B1 level in Spanish for travel',
    category: 'mind',
    colorTheme: 'lavender',
    deadline: new Date('2026-09-01'),
    isPublic: false,
    progress: 12,
    status: 'active',
    aiGenerated: false,
    smartData: null,
    projectId: null,
    createdAt: new Date('2026-03-15'),
    updatedAt: new Date('2026-03-27'),
    measurables: [
      { id: 'm4', goalId: '2', title: 'Duolingo sessions', type: 'counter', targetValue: 7, targetUnit: 'sessions', frequency: 'weekly', currentValue: 3, isAiSuggested: true, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() },
      { id: 'm5', goalId: '2', title: 'Watch Spanish media', type: 'habit', targetValue: null, targetUnit: null, frequency: 'daily', currentValue: 0, isAiSuggested: false, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
    ],
  },
  {
    id: '3',
    userId: 'mock-user',
    title: 'Ship Ohara MVP',
    description: 'Complete Phase 1 and launch friends & family pilot',
    category: 'create',
    colorTheme: 'ocean',
    deadline: new Date('2026-05-01'),
    isPublic: false,
    progress: 48,
    status: 'active',
    aiGenerated: false,
    smartData: null,
    projectId: null,
    createdAt: new Date('2026-02-01'),
    updatedAt: new Date('2026-03-28'),
    measurables: [
      { id: 'm6', goalId: '3', title: 'Features shipped', type: 'counter', targetValue: 12, targetUnit: 'features', frequency: 'once', currentValue: 5, isAiSuggested: false, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() },
      { id: 'm7', goalId: '3', title: 'Daily coding session', type: 'habit', targetValue: null, targetUnit: null, frequency: 'daily', currentValue: 1, isAiSuggested: false, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
    ],
  },
  {
    id: '4',
    userId: 'mock-user',
    title: 'Read 24 Books This Year',
    description: 'Two books per month across fiction and non-fiction',
    category: 'mind',
    colorTheme: 'forest',
    deadline: new Date('2026-12-31'),
    isPublic: true,
    progress: 21,
    status: 'active',
    aiGenerated: false,
    smartData: null,
    projectId: null,
    createdAt: new Date('2026-01-01'),
    updatedAt: new Date('2026-03-25'),
    measurables: [
      { id: 'm8', goalId: '4', title: 'Books completed', type: 'counter', targetValue: 24, targetUnit: 'books', frequency: 'once', currentValue: 5, isAiSuggested: false, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() },
    ],
  },
  {
    id: '5',
    userId: 'mock-user',
    title: 'Build a Savings Cushion',
    description: 'Save $5,000 emergency fund',
    category: 'money',
    colorTheme: 'slate',
    deadline: new Date('2026-08-01'),
    isPublic: false,
    progress: 60,
    status: 'active',
    aiGenerated: false,
    smartData: null,
    projectId: null,
    createdAt: new Date('2026-01-15'),
    updatedAt: new Date('2026-03-26'),
    measurables: [
      { id: 'm9', goalId: '5', title: 'Amount saved', type: 'counter', targetValue: 5000, targetUnit: 'dollars', frequency: 'once', currentValue: 3000, isAiSuggested: false, sortOrder: 0, createdAt: new Date(), updatedAt: new Date() },
      { id: 'm10', goalId: '5', title: 'Review budget weekly', type: 'habit', targetValue: null, targetUnit: null, frequency: 'weekly', currentValue: 1, isAiSuggested: true, sortOrder: 1, createdAt: new Date(), updatedAt: new Date() },
    ],
  },
];

export const MOCK_GOAL_ACTIVITIES: Record<string, ActivityEntry[]> = {
  '1': [
    {
      id: 'se1',
      goalId: '1',
      text: 'First run done! Only made it 1.5 miles but felt good to start. Legs were heavy but I pushed through the last quarter mile.',
      aiResponse: 'Starting is the hardest part and you did it. That last quarter mile when your legs were heavy — that is where the real training happens.',
      type: 'journal',
      createdAt: new Date('2026-03-25T18:30:00'),
    },
    {
      id: 'se2',
      goalId: '1',
      text: 'Skipped my run today. Work was brutal and I just could not find the energy. Feeling guilty about it.',
      aiResponse: 'Rest is part of training, not the absence of it. The guilt tells me this goal matters to you — that is more signal than one missed day.',
      type: 'journal',
      createdAt: new Date('2026-03-27T20:45:00'),
    },
    {
      id: 'se3',
      goalId: '1',
      text: 'Hit 2 miles today without stopping. Progress!',
      mediaUrl: 'https://placehold.co/400x300/E85D04/FFF?text=Run+Photo',
      type: 'journal',
      createdAt: new Date('2026-03-28T07:30:00'),
    },
  ],
};
