import { adaptGraphDtoToViewModel } from '../graph.ts';
import type { ConstellationLayoutSpec } from '../layout.ts';
import type {
  ConstellationAnnotationDTO,
  ConstellationEarnedNodeDTO,
  ConstellationGraphDTO,
  ConstellationGraphEdgeDTO,
  ConstellationVirtualBrtClusterDTO,
  GraphEdgeKind,
  GraphEdgeValence,
} from '../types.ts';

const FIRST_SEEN_AT = '2026-04-01T12:00:00.000Z';
const LAST_ACTIVITY_AT = '2026-07-27T18:00:00.000Z';

const earnedNodes: readonly ConstellationEarnedNodeDTO[] = [
  {
    id: 'renderer-season',
    selectionKey: 'node:renderer-season',
    kind: 'season',
    label: 'Season 03',
    description: '2026',
    authorship: 'system',
    isEarned: true,
    source: { type: 'season', id: null },
    visibilityScore: null,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  {
    id: 'renderer-ambition-health',
    selectionKey: 'node:renderer-ambition-health',
    kind: 'ambition',
    label: 'Body & Health',
    description: 'Build a durable relationship with movement and recovery.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'project', id: 'renderer-project-health' },
    visibilityScore: 8.4,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  {
    id: 'renderer-ambition-craft',
    selectionKey: 'node:renderer-ambition-craft',
    kind: 'ambition',
    label: 'Craft & Career',
    description: 'Make meaningful work with deliberate attention.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'project', id: 'renderer-project-craft' },
    visibilityScore: 8.1,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  {
    id: 'renderer-ambition-home',
    selectionKey: 'node:renderer-ambition-home',
    kind: 'ambition',
    label: 'Home & Relationships',
    description: 'Practice steady presence with the people who matter.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'project', id: 'renderer-project-home' },
    visibilityScore: 7.8,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  ...[
    ['train', 'Train three times weekly', 'renderer-goal-train-source'],
    ['cook', 'Cook five meals', 'renderer-goal-cook-source'],
    ['ship', 'Ship the first release', 'renderer-goal-ship-source'],
    ['read', 'Read twenty-four books', 'renderer-goal-read-source'],
    ['essay', 'Publish a weekly essay', 'renderer-goal-essay-source'],
    ['call', 'Call family every Sunday', 'renderer-goal-call-source'],
    ['date', 'Protect a weekly date night', 'renderer-goal-date-source'],
  ].map(([key, label, sourceId], index) => ({
    id: `renderer-goal-${key}`,
    selectionKey: `node:renderer-goal-${key}` as `node:${string}`,
    kind: 'goal' as const,
    label,
    description: 'Synthetic development goal for renderer QA.',
    authorship: 'system' as const,
    isEarned: true as const,
    source: {
      type: 'goal' as const,
      id: sourceId,
      goalStatus: 'active' as const,
    },
    visibilityScore: 7.6 - index * 0.2,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  })),
  ...[
    ['confidence', 'Confidence through consistency'],
    ['motion', 'Movement clears the fog'],
    ['isolation', 'Deep work needs isolation'],
    ['rituals', 'Care lives in small rituals'],
    ['recovery', 'Ambition needs recovery'],
  ].map(([key, label], index) => ({
    id: `renderer-reflection-${key}`,
    selectionKey: `node:renderer-reflection-${key}` as `node:${string}`,
    kind: 'reflection' as const,
    label,
    description: 'Synthetic validated pattern for renderer QA.',
    authorship: 'system' as const,
    isEarned: true as const,
    source: { type: 'candidate' as const, id: `renderer-candidate-${key}` },
    visibilityScore: 6.4 - index * 0.15,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  })),
  {
    id: 'renderer-trait-motion',
    selectionKey: 'node:renderer-trait-motion',
    kind: 'trait',
    label: 'Recovers through motion',
    description: 'A durable pattern carried across seasons.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'character_profile', id: 'renderer-profile' },
    visibilityScore: 7.1,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  {
    id: 'renderer-trait-maker',
    selectionKey: 'node:renderer-trait-maker',
    kind: 'trait',
    label: 'Late-night maker',
    description: 'A durable pattern carried across seasons.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'character_profile', id: 'renderer-profile' },
    visibilityScore: 6.9,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  {
    id: 'renderer-tension-discipline',
    selectionKey: 'node:renderer-tension-discipline',
    kind: 'tension',
    label: 'Discipline ↔ Compassion',
    description: 'A synthetic contradiction with evidence on both sides.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'candidate', id: 'renderer-candidate-tension-discipline' },
    visibilityScore: 8.2,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
  {
    id: 'renderer-tension-presence',
    selectionKey: 'node:renderer-tension-presence',
    kind: 'tension',
    label: 'Deep work ↔ Presence',
    description: 'A synthetic contradiction with evidence on both sides.',
    authorship: 'system',
    isEarned: true,
    source: { type: 'candidate', id: 'renderer-candidate-tension-presence' },
    visibilityScore: 8,
    firstSeenAt: FIRST_SEEN_AT,
    lastActivityAt: LAST_ACTIVITY_AT,
  },
];

const annotations: readonly ConstellationAnnotationDTO[] = [
  {
    id: 'renderer-projection-partner',
    selectionKey: 'annotation:renderer-projection-partner',
    kind: 'projection',
    status: 'draft',
    authorship: 'user',
    isDraft: true,
    label: 'A present partner',
    body: 'Synthetic draft projection for renderer QA.',
    anchorEarnedNodeId: null,
    anchorGoalId: 'renderer-goal-date',
    createdAt: LAST_ACTIVITY_AT,
    updatedAt: LAST_ACTIVITY_AT,
    archivedAt: null,
  },
  {
    id: 'renderer-note-quiet-hour',
    selectionKey: 'annotation:renderer-note-quiet-hour',
    kind: 'note',
    status: 'draft',
    authorship: 'user',
    isDraft: true,
    label: 'Protect the quiet hour',
    body: 'Synthetic draft note for renderer QA.',
    anchorEarnedNodeId: null,
    anchorGoalId: 'renderer-goal-ship',
    createdAt: LAST_ACTIVITY_AT,
    updatedAt: LAST_ACTIVITY_AT,
    archivedAt: null,
  },
];

const virtualBrtClusters: readonly ConstellationVirtualBrtClusterDTO[] = [
  ['train', 'bud', 'Bud', 1],
  ['train', 'rose', 'Rose', 1],
  ['train', 'thorn', 'Thorn', 1],
  ['ship', 'rose', 'Rose', 3],
  ['essay', 'thorn', 'Thorn', 3],
].map(([goalKey, category, label, count]) => ({
  id: `brt:renderer-goal-${goalKey}-source:${category}` as ConstellationVirtualBrtClusterDTO['id'],
  selectionKey: `brt:renderer-goal-${goalKey}-source:${category}` as ConstellationVirtualBrtClusterDTO['selectionKey'],
  goalId: `renderer-goal-${goalKey}-source`,
  goalNodeId: `renderer-goal-${goalKey}`,
  brtCategory: category,
  label,
  evidenceLinkCount: count,
  latestEvidenceAt: LAST_ACTIVITY_AT,
  isVirtual: true,
  isPersisted: false,
})) as readonly ConstellationVirtualBrtClusterDTO[];

type EarnedEdgeKind = Exclude<
  GraphEdgeKind,
  'annotation_anchor' | 'goal_evidence_cluster'
>;

function earnedEdge(
  id: string,
  from: string,
  to: string,
  kind: EarnedEdgeKind,
  valence: GraphEdgeValence | null,
  weight: number | null,
): ConstellationGraphEdgeDTO {
  return {
    id,
    from: { entityType: 'earned_node', id: from },
    to: { entityType: 'earned_node', id: to },
    kind,
    valence,
    weight,
    isPersisted: false,
  } as ConstellationGraphEdgeDTO;
}

function annotationEdge(
  id: string,
  annotationId: string,
  earnedNodeId: string,
): ConstellationGraphEdgeDTO {
  return {
    id,
    from: { entityType: 'annotation', id: annotationId },
    to: { entityType: 'earned_node', id: earnedNodeId },
    kind: 'annotation_anchor',
    valence: null,
    weight: null,
    isPersisted: false,
  };
}

function brtEdge(
  goalKey: string,
  category: 'bud' | 'rose' | 'thorn',
): ConstellationGraphEdgeDTO {
  return {
    id: `renderer-edge-${goalKey}-${category}`,
    from: { entityType: 'earned_node', id: `renderer-goal-${goalKey}` },
    to: {
      entityType: 'virtual_brt_cluster',
      id: `brt:renderer-goal-${goalKey}-source:${category}`,
    },
    kind: 'goal_evidence_cluster',
    valence: null,
    weight: null,
    isPersisted: false,
  };
}

const edges: readonly ConstellationGraphEdgeDTO[] = [
  earnedEdge('edge-season-health', 'renderer-season', 'renderer-ambition-health', 'season_membership', null, null),
  earnedEdge('edge-season-craft', 'renderer-season', 'renderer-ambition-craft', 'season_membership', null, null),
  earnedEdge('edge-season-home', 'renderer-season', 'renderer-ambition-home', 'season_membership', null, null),
  earnedEdge('edge-health-train', 'renderer-ambition-health', 'renderer-goal-train', 'ambition_goal', 'positive', 7),
  earnedEdge('edge-health-cook', 'renderer-ambition-health', 'renderer-goal-cook', 'ambition_goal', 'mixed', 5),
  earnedEdge('edge-craft-ship', 'renderer-ambition-craft', 'renderer-goal-ship', 'ambition_goal', 'mixed', 7),
  earnedEdge('edge-craft-read', 'renderer-ambition-craft', 'renderer-goal-read', 'ambition_goal', 'positive', 4),
  earnedEdge('edge-craft-essay', 'renderer-ambition-craft', 'renderer-goal-essay', 'ambition_goal', 'positive', 5),
  earnedEdge('edge-home-call', 'renderer-ambition-home', 'renderer-goal-call', 'ambition_goal', 'positive', 6),
  earnedEdge('edge-home-date', 'renderer-ambition-home', 'renderer-goal-date', 'ambition_goal', 'positive', 6),
  earnedEdge('edge-train-confidence', 'renderer-goal-train', 'renderer-reflection-confidence', 'goal_pattern', 'positive', 7),
  earnedEdge('edge-train-motion', 'renderer-goal-train', 'renderer-reflection-motion', 'goal_pattern', 'positive', 8),
  earnedEdge('edge-cook-motion', 'renderer-goal-cook', 'renderer-reflection-motion', 'goal_pattern', 'positive', 4),
  earnedEdge('edge-ship-isolation', 'renderer-goal-ship', 'renderer-reflection-isolation', 'goal_pattern', 'mixed', 6),
  earnedEdge('edge-ship-maker', 'renderer-goal-ship', 'renderer-trait-maker', 'goal_pattern', 'positive', 5),
  earnedEdge('edge-read-rituals', 'renderer-goal-read', 'renderer-reflection-rituals', 'goal_pattern', 'neutral', 3),
  earnedEdge('edge-essay-recovery', 'renderer-goal-essay', 'renderer-reflection-recovery', 'goal_pattern', 'mixed', 5),
  earnedEdge('edge-date-rituals', 'renderer-goal-date', 'renderer-reflection-rituals', 'goal_pattern', 'positive', 5),
  earnedEdge('edge-confidence-motion', 'renderer-reflection-confidence', 'renderer-reflection-motion', 'pattern_cooccurrence', 'positive', 6),
  earnedEdge('edge-isolation-rituals', 'renderer-reflection-isolation', 'renderer-reflection-rituals', 'pattern_cooccurrence', 'mixed', 4),
  earnedEdge('edge-recovery-rituals', 'renderer-reflection-recovery', 'renderer-reflection-rituals', 'pattern_cooccurrence', 'positive', 5),
  earnedEdge('edge-motion-trait', 'renderer-reflection-motion', 'renderer-trait-motion', 'trait_derivation', 'positive', 8),
  earnedEdge('edge-isolation-trait', 'renderer-reflection-isolation', 'renderer-trait-maker', 'trait_derivation', 'mixed', 6),
  earnedEdge('edge-tension-discipline-motion', 'renderer-tension-discipline', 'renderer-reflection-motion', 'tension_composition', 'contradictory', 5),
  earnedEdge('edge-tension-discipline-recovery', 'renderer-tension-discipline', 'renderer-reflection-recovery', 'tension_composition', 'contradictory', 5),
  earnedEdge('edge-tension-presence-isolation', 'renderer-tension-presence', 'renderer-reflection-isolation', 'tension_composition', 'contradictory', 6),
  earnedEdge('edge-tension-presence-rituals', 'renderer-tension-presence', 'renderer-reflection-rituals', 'tension_composition', 'contradictory', 5),
  annotationEdge('edge-projection-date', 'renderer-projection-partner', 'renderer-goal-date'),
  annotationEdge('edge-note-ship', 'renderer-note-quiet-hour', 'renderer-goal-ship'),
  brtEdge('train', 'bud'),
  brtEdge('train', 'rose'),
  brtEdge('train', 'thorn'),
  brtEdge('ship', 'rose'),
  brtEdge('essay', 'thorn'),
];

export const constellationRendererFixtureGraphDTO: ConstellationGraphDTO = {
  version: '1.0',
  state: {
    hasGraphData: true,
    renderState: 'graph',
    phase: 'initial_read_only',
    dataOrigin: 'real',
    generatedAt: LAST_ACTIVITY_AT,
    dataAsOf: LAST_ACTIVITY_AT,
    seasonNodeId: 'renderer-season',
  },
  earnedNodes,
  annotations,
  virtualBrtClusters,
  edges,
  counts: {
    earnedNodes: {
      total: 20,
      byKind: {
        season: 1,
        ambition: 3,
        goal: 7,
        reflection: 5,
        trait: 2,
        tension: 2,
      },
    },
    annotations: { draft: 2, archived: 0 },
    virtualBrtClusters: { total: 5, bud: 1, rose: 2, thorn: 2 },
    edges: edges.length,
    evidenceLinks: 9,
    source: {
      echoEntries: 18,
      qualifiedCandidates: 9,
      goalsByStatus: {
        active: 7,
        draft: 0,
        complete: 0,
        stagnant: 0,
        discovered: 0,
        archived: 0,
      },
    },
  },
};

export const constellationRendererFixtureGraph = adaptGraphDtoToViewModel(
  constellationRendererFixtureGraphDTO,
  { renderBudget: 30 },
);

export const constellationRendererFixtureLayoutSpec: ConstellationLayoutSpec = {
  nodePositions: {
    'node:renderer-season': { x: 0.55, y: 0.51 },
    'node:renderer-ambition-health': { x: 0.27, y: 0.39 },
    'node:renderer-ambition-craft': { x: 0.76, y: 0.38 },
    'node:renderer-ambition-home': { x: 0.56, y: 0.78 },
    'node:renderer-goal-train': { x: 0.18, y: 0.18 },
    'node:renderer-goal-cook': { x: 0.27, y: 0.59 },
    'node:renderer-goal-ship': { x: 0.88, y: 0.18 },
    'node:renderer-goal-read': { x: 0.93, y: 0.46 },
    'node:renderer-goal-essay': { x: 0.84, y: 0.65 },
    'node:renderer-goal-call': { x: 0.4, y: 0.88 },
    'node:renderer-goal-date': { x: 0.7, y: 0.88 },
    'node:renderer-reflection-confidence': { x: 0.31, y: 0.14 },
    'node:renderer-reflection-motion': { x: 0.38, y: 0.56 },
    'node:renderer-reflection-isolation': { x: 0.78, y: 0.13 },
    'node:renderer-reflection-rituals': { x: 0.68, y: 0.64 },
    'node:renderer-reflection-recovery': { x: 0.89, y: 0.72 },
    'node:renderer-trait-motion': { x: 0.43, y: 0.3 },
    'node:renderer-trait-maker': { x: 0.77, y: 0.27 },
    'node:renderer-tension-discipline': { x: 0.34, y: 0.68 },
    'node:renderer-tension-presence': { x: 0.6, y: 0.23 },
    'annotation:renderer-projection-partner': { x: 0.59, y: 0.62 },
    'annotation:renderer-note-quiet-hour': { x: 0.71, y: 0.1 },
    'brt:renderer-goal-train-source:bud': { x: 0.08, y: 0.27 },
    'brt:renderer-goal-train-source:rose': { x: 0.2, y: 0.31 },
    'brt:renderer-goal-train-source:thorn': { x: 0.11, y: 0.39 },
    'brt:renderer-goal-ship-source:rose': { x: 0.91, y: 0.29 },
    'brt:renderer-goal-essay-source:thorn': { x: 0.94, y: 0.58 },
  },
  edgeBends: {
    'edge-season-health': -0.05,
    'edge-season-craft': 0.04,
    'edge-season-home': 0.02,
    'edge-health-train': 0.03,
    'edge-health-cook': -0.03,
    'edge-craft-ship': -0.04,
    'edge-craft-read': 0.03,
    'edge-craft-essay': -0.04,
    'edge-home-call': -0.04,
    'edge-home-date': 0.04,
    'edge-confidence-motion': 0.05,
    'edge-tension-discipline-motion': -0.05,
    'edge-tension-presence-isolation': 0.05,
  },
};

export const CONSTELLATION_RENDERER_INITIAL_SELECTION = 'node:renderer-goal-train';
